# Final Project: Spotify Top Songs Analysis

## Exploratory Analysis

In [1]:
# Import dependencies
import pandas as pd
import psycopg2
import numpy as np

### Load in data from database

In [2]:
from sqlalchemy import create_engine
from getpass import getpass

# Set up connection to database
password = getpass('Enter database password.')
engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/project_spotify_db')

Enter database password.········

In [3]:
# Read in Spotify song data from database
song_df = pd.read_sql('SELECT * FROM top_songs;', engine, index_col='Index')
song_df.head()

,song_id,song_name,artist,number_of_times_charted,highest_charting_position,week_of_highest_charting_start,week_of_highest_charting_end,number_weeks_charted,streams,artist_followers,...,acousticness,danceability,energy,liveness,loudness,speechiness,valence,duration_ms,tempo,chord
Index,,,,,,,,,,,,,,,,,,,,,
1,3Wrjm47oTz2sjIgck11l5e,Beggin',Måneskin,8,1,2021-07-23,2021-07-30,8,48633449,3377762,...,0.1270,0.714,0.800,0.3590,-4.808,0.0504,0.589,211560,134.002,B
2,5HCyWlXZPP0y6Gqq8TgA20,STAY (with Justin Bieber),The Kid LAROI,3,2,2021-07-23,2021-07-30,3,47248719,2230022,...,0.0383,0.591,0.764,0.1030,-5.484,0.0483,0.478,141806,169.928,C#/Db
3,4ZtFanR9U6ndgddUvNcjcG,good 4 u,Olivia Rodrigo,11,1,2021-06-25,2021-07-02,11,40162559,6266514,...,0.3350,0.563,0.664,0.0849,-5.044,0.1540,0.688,178147,166.928,A
4,6PQ88X9TkUIAUIZJHW2upE,Bad Habits,Ed Sheeran,5,3,2021-07-02,2021-07-09,5,37799456,83293380,...,0.0469,0.808,0.897,0.3640,-3.712,0.0348,0.591,231041,126.026,B
5,27NovPIUIRrOZoCHxABJwK,INDUSTRY BABY (feat. Jack Harlow),Lil Nas X,1,5,2021-07-23,2021-07-30,1,33948454,5473565,...,0.0203,0.736,0.704,0.0501,-7.409,0.0615,0.894,212000,149.995,D#/Eb

### Song Analysis

#### What songs have charted the most?

In [4]:
song_number_charted_df = song_df[['song_id', 'song_name', 'artist', 'number_of_times_charted']]
song_number_charted_df = song_number_charted_df.sort_values(['number_of_times_charted'], ascending=False)
song_number_charted_df.head(10)

,song_id,song_name,artist,number_of_times_charted
Index,,,,
369,1ZMiCix7XSAbfAJlEZWMCp,Falling,Harry Styles,142
93,21jGcNKet2qwijlDFuPiPb,Circles,Post Malone,84
162,285pBltuF7vW8TeWk8hdRR,Lucid Dreams,Juice WRLD,83
25,0VjIjW4GlUZAMYd2vXMi3b,Blinding Lights,The Weeknd,83
118,0TK2YIli7K1leLovkQiNik,Señorita,"Shawn Mendes, Camila Cabello",83
112,3KkXRkHbMCARz0aVfEt68P,Sunflower - Spider-Man: Into the Spider-Verse,"Post Malone, Swae Lee",83
111,0u2P5u6lvoDfwTYjAADbn4,lovely (with Khalid),Billie Eilish,83
133,4cktbXiXOapiLBMprHFErI,Memories,Maroon 5,83
107,0zLCBJZSiELJf02ucPP9wb,Roses - Imanbek Remix,SAINt JHN,83
104,0pqnGHJpmpxLKifKRmU6WP,Believer,Imagine Dragons,83

Most charted song since Jan. 2020: 'Falling' by Harry Styles

#### What songs have the highest number of streams?

In [5]:
song_streams_df = song_df[['song_id', 'song_name', 'artist', 'streams']]
song_streams_df = song_streams_df.sort_values(['streams'], ascending=False)
song_streams_df.head(10)

,song_id,song_name,artist,streams
Index,,,,
1,3Wrjm47oTz2sjIgck11l5e,Beggin',Måneskin,48633449
2,5HCyWlXZPP0y6Gqq8TgA20,STAY (with Justin Bieber),The Kid LAROI,47248719
3,4ZtFanR9U6ndgddUvNcjcG,good 4 u,Olivia Rodrigo,40162559
4,6PQ88X9TkUIAUIZJHW2upE,Bad Habits,Ed Sheeran,37799456
5,27NovPIUIRrOZoCHxABJwK,INDUSTRY BABY (feat. Jack Harlow),Lil Nas X,33948454
6,67BtfxlNbhBmCDR2L2l8qd,MONTERO (Call Me By Your Name),Lil Nas X,30071134
7,748mdHapucXQri7IAO8yFK,Kiss Me More (feat. SZA),Doja Cat,29356736
1431,4umIPjkehX1r7uhmGvXiSV,Intentions,"Justin Bieber, Quavo",28509534
8,4fSIb4hdOQ151TILNsSEaF,Todo De Ti,Rauw Alejandro,26951613
9,2JPLbjOn0wPCngEot2STUS,Yonaguni,Bad Bunny,25030128

Song with most streams since Jan. 2020: 'Beggin'' by Måneskin

### Artist Analysis

In [6]:
# Create copy of dataframe focusing on artist info
artist_df = song_df[['song_id', 'song_name', 'artist', 'number_of_times_charted', 'highest_charting_position', 'number_weeks_charted', 'streams', 'artist_followers']]
artist_df.head()

,song_id,song_name,artist,number_of_times_charted,highest_charting_position,number_weeks_charted,streams,artist_followers
Index,,,,,,,,
1,3Wrjm47oTz2sjIgck11l5e,Beggin',Måneskin,8,1,8,48633449,3377762
2,5HCyWlXZPP0y6Gqq8TgA20,STAY (with Justin Bieber),The Kid LAROI,3,2,3,47248719,2230022
3,4ZtFanR9U6ndgddUvNcjcG,good 4 u,Olivia Rodrigo,11,1,11,40162559,6266514
4,6PQ88X9TkUIAUIZJHW2upE,Bad Habits,Ed Sheeran,5,3,5,37799456,83293380
5,27NovPIUIRrOZoCHxABJwK,INDUSTRY BABY (feat. Jack Harlow),Lil Nas X,1,5,1,33948454,5473565

#### Which artist has the most charted songs?

In [7]:
artist_charted_grouped = artist_df[['artist', 'song_name']].groupby(['artist'])

# Convert GroupBy object into DataFrame
artist_songs_count_df = pd.DataFrame(artist_charted_grouped['song_name'].count())
artist_songs_count_df = artist_songs_count_df.rename(columns={'song_name':'count_of_charted_songs'})
artist_songs_count_df = artist_songs_count_df.sort_values(['count_of_charted_songs'], ascending=False)
artist_songs_count_df.head(10)

               count_of_charted_songs
artist
Taylor Swift                       52
Lil Uzi Vert                       32
Justin Bieber                      32
Juice WRLD                         30
BTS                                29
Pop Smoke                          29
Bad Bunny                          28
Eminem                             22
The Weeknd                         21
Drake                              19

Artist with most charted songs since Jan. 2020: Taylor Swift

#### Which artist has the most streams?

In [8]:
artist_streams_grouped = artist_df[['artist', 'streams']].groupby(['artist'])

# Convert GroupBy object into DataFrame
artist_streams_total_df = pd.DataFrame(artist_streams_grouped['streams'].sum())
artist_streams_total_df = artist_streams_total_df.sort_values(['streams'], ascending=False)
artist_streams_total_df.head(10)

                  streams
artist
Taylor Swift    381480455
BTS             238400020
Justin Bieber   225842427
Lil Uzi Vert    208822039
Bad Bunny       203813133
Pop Smoke       173634217
Juice WRLD      166703004
Olivia Rodrigo  163685977
Eminem          162935796
The Weeknd      149088439

Artist with the most streams since Jan. 2020: Taylor Swift

#### Which artists have the most #1 hits?

In [9]:
# Create dataframe of number one songs only
artist_hits_df = artist_df.loc[artist_df["highest_charting_position"] == 1, ['artist', 'song_name', 'highest_charting_position']]
artist_hits_df.head()

,artist,song_name,highest_charting_position
Index,,,
1,Måneskin,Beggin',1
3,Olivia Rodrigo,good 4 u,1
6,Lil Nas X,MONTERO (Call Me By Your Name),1
14,Justin Bieber,Peaches (feat. Daniel Caesar & Giveon),1
23,Olivia Rodrigo,drivers license,1

In [11]:
artist_hits_grouped = artist_hits_df[['artist', 'song_name']].groupby(['artist'])

# Convert GroupBy object into DataFrame
total_hits_by_artist_df = pd.DataFrame(artist_hits_grouped['song_name'].count())
total_hits_by_artist_df = total_hits_by_artist_df.rename(columns={'song_name':'count_of_number_ones'})
total_hits_by_artist_df = total_hits_by_artist_df.sort_values(['count_of_number_ones'], ascending=False)
total_hits_by_artist_df.head(10)

                                    count_of_number_ones
artist
Olivia Rodrigo                                         2
24kGoldn                                               1
Mariah Carey                                           1
The Weeknd                                             1
Taylor Swift                                           1
THE SCOTTS, Travis Scott, Kid Cudi                     1
Roddy Ricch                                            1
Måneskin                                               1
Lil Nas X                                              1
Ariana Grande                                          1

Artist with most #1 hits since Jan. 2020: Olivia Rodrigo

#### Which artists have the most followers?

In [14]:
artist_followers_grouped = artist_df[['artist', 'artist_followers']].groupby(['artist'])

# Convert GroupBy object into DataFrame
artist_followers_df = pd.DataFrame(artist_followers_grouped['artist_followers'].sum())
artist_followers_df = artist_followers_df.sort_values(['artist_followers'], ascending=False)
artist_followers_df.head(10)

               artist_followers
artist
Taylor Swift         2195835928
Justin Bieber        1458726005
Ariana Grande        1209646856
BTS                  1077075704
Drake                1070157012
Eminem               1029836952
Bad Bunny            1012869619
The Weeknd            742003721
Ed Sheeran            667819408
Juice WRLD            572980020

Artist with the most followers: Taylor Swift